### ISSUE TITLE
Hello, when will you release the codes for training?

### ISSUE THREAD

**Issue by nikki0205** [facebookresearch/audioseal#12]
I'm very interested in your work and want to train my own models based on the project. Could you tell me how to do it?
Thanks a lot!

**Comment by antoine-tran** [comment]
Hi, we expect to release the training code in a few weeks (also subject to legal approval process in Meta). Stay tuned !

**Comment by dlion168** [comment]
Hi, I am also reaaly interested in this project. Is there any plan to release the training pipeline recently?

**Comment by pierrefdz** [comment]
Hi!
The code is ready, but we are still waiting for coms and legal approvals. Sorry about the delay... hopefully in the following days/ weeks it will be approved.

**Comment by faabian** [comment]
The code is not yet merged but I noticed it was here:
https://github.com/facebookresearch/audiocraft/pull/464

**Comment by pierrefdz** [comment]
https://github.com/facebookresearch/audiocraft/pull/464

**Comment by antoine-tran** [comment]
The training code is now ready, check the [instruction](https://github.com/facebookresearch/audioseal/blob/main/docs/TRAINING.md)
