### ISSUE TITLE
Radio Silence from the Facebook Research Team

### ISSUE THREAD

**Issue by KabaTubare** [facebookresearch/audioseal#15]
Respectfully, this is my second message, as well as several outreaches on X (Twitter). This project results in 100% false positives despite threshold settings, and I am a bit concerned no one has gotten back to me especially given that the model does not seem to be ready and requires further real-world-use-case testing. Is it possible to have a discussion? Thanks, tw

**Comment by robinsrm** [comment]
Hi @KabaTubare :) 

@hadyelsahar responded to your first issue, we can't do much if you do not give us your code and audio samples. 

I am closing this issue to avoid duplicates see: https://github.com/facebookresearch/audioseal/issues/14

Robin
