### ISSUE TITLE
Unable to identify previously audioseal watermarked files

### ISSUE THREAD

**Issue by KabaTubare** [facebookresearch/audioseal#19]
Here is the notebook code: https://colab.research.google.com/gist/KabaTubare/13d0ef6ecb132a8c1a73bb143352c10c/audioseal-inference.ipynb

**Comment by KabaTubare** [comment]
<img width="1108" alt="Screenshot 2024-02-29 at 8 27 29" src="https://github.com/facebookresearch/audioseal/assets/130111190/cef104bc-7893-42a1-b28d-baa10ef1b02b">

**Comment by pierrefdz** [comment]
Hi @KabaTubare, 

We appreciate your enthusiasm for improving the project, but it's important to remember that the issue tracker is intended for reporting specific bugs or feature requests. Would you mind reading [the paper](https://arxiv.org/abs/2401.17264) first? This will answer most of your questions.

Thank you for your understanding and cooperation.

**Comment by antoine-tran** [comment]
Hi @KabaTubare , is your concern with the detector resolved ? If so, I would like to close this issue

**Comment by KabaTubare** [comment]
Hey there!

Yes, I have a demo up and running on HF already🙌🏽🖖🏾

Kind regards,

Troy Woodson
