### ISSUE TITLE
Support for 48k Hz Audio

### ISSUE THREAD

**Issue by RohitMidha23** [facebookresearch/audioseal#26]
Is there a way to use this for 48k HZ audio without losing out information?

**Comment by RohitMidha23** [comment]
The example usage mentions: 
```python
# It is important to process the audio to the same sample rate as the model
# expectes. In our case, we support 16khz audio 
```
Hence the question..

**Comment by pierrefdz** [comment]
Thanks for putting this to our attention.
We recently updated the code to work for different sampling rates, and we forgot to update the example in the readme. We'll change it in a future update.

In our tests, this results in a decrease of detection performance. In my opinion, this may be solved by quickly fine-tuning the model on your audios with different sampling rates (the training code for the models should be released in the coming weeks/ months).

**Comment by RohitMidha23** [comment]
Looking forward to the model release. Thanks!
