### ISSUE TITLE
Beyond 16 bits

### ISSUE THREAD

**Issue by KabaTubare** [facebookresearch/audioseal#29]
Hi 

I have created an application based on this model and wonder on your plans for over 16 bits?
Kindly

**Comment by KabaTubare** [comment]
Hi there! That is great news. Any chance for the community of builders to
know? I have built a full stack application based off this model

Kind regards,

Troy Woodson

**Comment by antoine-tran** [comment]
The training code is now available with instruction. See https://github.com/facebookresearch/audioseal/blob/main/docs/TRAINING.md for more details
